- name: Create kube config directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.kube/"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'

- name: Copy admin.conf to $HOME/.kube
  ansible.builtin.copy:
    src: '/etc/kubernetes/admin.conf'
    dest: "{{ lookup('env', 'HOME') }}/.kube/config"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0600'
    remote_src: true
  become: true

# - name: Print result of kubeadm init
#   ansible.builtin.debug:
#     msg: '{{ kubeadm_init.stdout }}'

# - name:
