- name: Setup ubuntu machine
  hosts: all
  gather_facts: false

  roles:
    - name: ubuntu
    - name: containerd
      when: containerd is defined
    - name: runc
      when: runc is defined
    - name: cni_plugins
      when: cni_plugins is defined
    - name: apt
      when: kubernetes is defined

- name: Setup controlplane
  hosts: controlplane
  gather_facts: false

  roles:
    - name: kubelet

- name: Setup woker nodes
  hosts: workers
  gather_facts: false

  roles:
