- name: Setup ubuntu machine
  hosts: all
  gather_facts: false

  roles:
    - name: ssh
    - name: containerd
      when: containerd is defined
    - name: runc
      when: runc is defined
    - name: cni_plugins
      when: cni_plugins is defined
    - name: apt
