- name: Setup controlplane
  become: true
  block:
    - name: Check if kubernetes is already installed
      ansible.builtin.stat:
        path: '{{ controlplane_admin_conf }}'
      register: admin_conf

    - name: Initialize Kubernetes controlplane
      ansible.builtin.command: 'kubeadm init --pod-network-cidr={{ pod_network_cidr }}'
      changed_when: kubeadm_init.rc == 0
      register: kubeadm_init
      when: not admin_conf.stat.exists
      notify:
        - Create kube config directory
        - Copy admin.conf to $HOME/.kube
        # TODO:
        # - Save kubeadm token

# - name: Install Calico operator
#   ansible.builtin.command: 'kubectl create -f {{ controlplane_calico_operator }}'
#   changed_when: true

# - name: Install Calico CRD
#   ansible.builtin.command: 'kubectl create -f {{ controlplane_calico_crd }}'
#   changed_when: true
