- name: Configure kubelet args
  ansible.builtin.lineinfile:
    path: '{{ kubelet_arg_config_path }}'
    regexp: '^KUBELET_EXTRA_ARGS='
    line: "KUBELET_EXTRA_ARGS=--cgroup-driver=systemd"
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: true
  register: configure_kubelet_args

- name: Restart kubelet service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: kubelet
    state: restarted
  become: true
  when: configure_kubelet_args is changed
