# - name: Get hostname
#   ansible.builtin.command: hostname
#   register: hostname_result
#   changed_when: false

# - name: Print hostname to console
#   ansible.builtin.debug:
#     msg: "Hostname fo {{ inventory_hostname }}: {{ hostname_result.stdout }}"
#   changed_when: false

- name: Setup kernel parameter
  become: true
  block:
    - name: Create module conf if it does not exist
      ansible.builtin.copy:
        src: files/module.conf
        dest: "{{ ssh_module_conf_path }}"
        owner: root
        group: root
        mode: '0644'
      register: create_module_conf

    - name: Reflect modules to kernel
      ansible.builtin.command: "modprobe {{ module_name }}"
      loop: "{{ modules }}"
      loop_control:
        loop_var: module_name
      when:
        - create_module_conf is changed
        - modules is defined

    - name: Create sysctl conf if it does not exist
      ansible.builtin.copy:
        src: files/sysctl.conf
        dest: "{{ ssh_sysctl_conf_path }}"
        owner: root
        group: root
        mode: '0644'
      register: create_sysctl_conf

    - name: Reload sysctl settings
      ansible.builtin.command: sysctl --system
      register: reload_sysctl
      when: create_sysctl_conf is changed
      changed_when: reload_sysctl.rc != 0
