controlplane_admin_conf: '/etc/kubernetes/admin.conf'
controlplane_calico_github: 'https://raw.githubusercontent.com/projectcalico/calico'
controlplane_calico_operator: '{{ controlplane_calico_github }}/v{{ calico_version }}/manifests/tigera-operator.yaml'
controlplane_calico_crd: '{{ controlplane_calico_github }}/v{{ calico_version }}/manifests/custom-resources.yaml'
controlplane_kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"
