- name: Check if containerd is installed
  ansible.builtin.command: containerd --version
  register: containerd_check
  failed_when: false
  changed_when: false

- name: Download containerd archive
  ansible.builtin.get_url:
    url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-arm64.tar.gz"
    dest: /tmp/
    mode: '0664'
  register: download_archive
  when: containerd_check.rc != 0

- name: Unarchive containerd archive
  ansible.builtin.unarchive:
    src: /tmp/containerd-{{ containerd_version }}-linux-arm64.tar.gz
    dest: /usr/local
    remote_src: true
  when: download_archive is changed
  become: true

- name: Create an unit file directory
  ansible.builtin.file:
    path: /usr/local/lib/systemd/system/
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true
  register: containerd_service

- name: Download containerd systemd unit file
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
    dest: /usr/local/lib/systemd/system/
    mode: '0644'
  become: true
  register: download_containerd_service_file
  when: containerd_service is changed

- name: Ensure containerd service is enable and running
  ansible.builtin.systemd_service:
    daemon-reload: true
    name: containerd
    enabled: true
    state: started
  become: true
  register: start_containerd
  when: download_containerd_service_file is skipped

- name: Create a config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true
  register: containerd_config

- name: Standard out default config
  ansible.builtin.command: containerd config default
  changed_when: false
  register: stdout_default_config
  when:
    - start_containerd is succeeded
    - containerd_config is changed

- name: Create a default config file
  ansible.builtin.copy:
    content: "{{ stdout_default_config.stdout }}"
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  become: true
  when: stdout_default_config is not skipped
